config/routes.rb
Rails.application.routes.draw do
  resources 'topics', only: %i(index show new create) do
    resources :replies, only: :create
  end

  resources 'nodes', only: :show
  resources 'users', only: %i(show create) do
    get :topics
  end
  resources :sessions, only: :create

  get 'sign_up', to: 'users#new'
  get 'sign_in', to: 'sessions#new'
  delete 'sign_out', to: 'sessions#destroy'

  resources 'ui', only: :index
  get 'ui/:action', controller: 'ui'

  root to: 'topics#index'
end

app/models/node.rb
class Node < ActiveRecord::Base
  has_many :topics
end

app/models/reply.rb
class Reply < ActiveRecord::Base
  belongs_to :topic
  belongs_to :user

  default_scope { order(created_at: :desc) }
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :node
  belongs_to :user
  has_many :replies

  def last_reply
    replies.order(created_at: :desc).last
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :topics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user
    User.find session[:user_id] if session[:user_id].present?
  end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  def show
    @node = Node.find params[:id]
  end
end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  def create
    topic = Topic.find params[:topic_id]
    topic.replies.create params.require(:reply).permit(:content).merge(user_id: current_user.id)

    redirect_to topic
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    session[:user_id] = User.find_by(name: params[:user_name]).id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  def index
    @topics = Topic.all
  end

  def show
    @topic = Topic.find params[:id]
  end

  def new
    @topic = Topic.new
  end

  def create
    current_user.topics.create! params.require(:topic).permit(:node_id, :title, :body)
    redirect_to topics_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
  end

  def new
    @user = User.new
  end

  def create
    User.create! params.require(:user).permit(:name, :email)
    redirect_to root_path
  end

  def topics
    @user = User.find params[:user_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include LetterAvatar::AvatarHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    meta content="text/html; charset=UTF-8" http-equiv="Content-Type"
    title RailsDemo
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    nav.navbar.navbar-inverse.navbar-fixed-top
      .container
        .navbar-header
          button.navbar-toggle.collapsed type: "button" "data-toggle": "collapse" "data-target": "#navbar" "aria-expanded": "false" "aria-controls": "navbar"
            span
              Toggle navigatioon
            span.icon-bar
            span.icon-bar
            span.icon-bar
          a.navbar-brand href='/' RailsDemo
        ul.nav.navbar-nav.navbar-right
          - if current_user
            li.dropdown
              a.dropdown-toggle data-toggle='dropdown' id='userDropdownMenu'
                |blueplanet
                span.caret
              ul.dropdown-menu aria-labelledby='userDropdownMenu'
                li = link_to '我的主页', current_user
                li = link_to '退出', sign_out_path, method: :delete
          - else
            li = link_to '登录', sign_in_path
            li = link_to '注册新用户', sign_up_path
          
    .container
      == yield

app/views/nodes/show.html.slim
.row
  .col-md-9
    .panel.panel-default
      .panel-heading
        .node-info
          .name
            strong = @node.name
            span.total 共有 167 个讨论主题
          .summary
            p = @node.description
      .panel-body.topics
        .media-list
          - @node.topics.each do |topic|
            .media.topic
              .media-left
                a href='#'
                  = image_tag letter_avatar_url('hzbook')
              .media-body
                h4.media-heading
                  = link_to topic.title
                .info
                  a href='hzbook' hzbook
                  |・
                  |Last by 
                  a<> href='hzbook' hzbook
                  = "Created at #{time_ago_in_words topic.created_at} ago"
              .media-right
                .badge.badge-default.count 30

  .col-md-3
    .panel.panel-default
      .panel-body.text-center
        .row
          .col-md-12
            a href='/ui/new_topic' class='btn btn-primary btn-block' 发表新帖子
    .panel.panel-default
      .panel-heading 会员信息
      ul.list-group
        li.list-group-item 社区会员: 25426 人
        li.list-group-item 帖子数: 29278 个
        li.list-group-item 回帖数: 290719 条

app/views/topics/index.html.slim
.row
  .col-md-9
    .panel.panel-default
      .panel-heading 全部帖子
      .panel-body.topics
        .media-list
          - @topics.each do |topic|
            .media.topic
              .media-left
                a href='#'
                  = image_tag letter_avatar_url('hzbook')
              .media-body
                h4.media-heading
                  = link_to topic.title, topic
                .info
                  = link_to topic.node.name, topic.node, class: 'node'
                  |・
                  = link_to topic.user.name, topic.user
                  |・
                  = "创建于 #{time_ago_in_words topic.created_at} 之前"
                  - if topic.last_reply.present?
                    |・最新由
                    =<> link_to topic.last_reply.user.name, topic.last_reply.user
                    = "回复于 #{time_ago_in_words topic.last_reply.created_at} 之前"
              .media-right
                .badge.badge-default.count 30

    .panel.panel-default
      .panel-heading 节点列表
      .panel-body.node-list
        span.node-item
          a href='/topics/node1' 重构
        span.node-item
          a href='/topics/node2' Rails
        span.node-item
          a href='/topics/node3' RVM/Rbenv
        span.node-item
          a href='/topics/node4' JRuby
        span.node-item
          a href='/topics/node5' 新手问题
        span.node-item
          a href='/topics/node6' Gem
        span.node-item
          a href='/topics/node7' 开源项目
        span.node-item
          a href='/topics/node8' 部署

  .col-md-3
    .panel.panel-default
      .panel-body.text-center
        .row
          .col-md-12
            a href='/ui/new_topic' class='btn btn-primary btn-block' 发表新帖子
    .panel.panel-default
      .panel-heading 会员信息
      ul.list-group
        li.list-group-item 社区会员: 25426 人
        li.list-group-item 帖子数: 29278 个
        li.list-group-item 回帖数: 290719 条

app/views/topics/new.html.slim
.panel.panel-default
  .panel-heading 发布新话题
  .panel-body
    = form_for @topic do |f|
      .form-group
        .row
          .col-md-2
            = f.collection_select :node_id, Node.all, :id, :name, {}, class: 'form-control'
          .col-md-10
            = f.text_field :title, class: 'form-control', placeholder: '在这里填写标题'
      .form-group
        = f.text_area :body, rows: 20, class: 'form-control'
      .form-group
        .row
          .col-md-2
            = f.submit '保存', class: 'btn btn-primary btn-block'
          

app/views/topics/show.html.slim
.row
  .col-md-9
    .panel.panel-default.topic-detail
      .panel-heading.media
        .media-body
          h1.media-heading = @topic.title
          .info
            = link_to @topic.node.name, @topic.node, class: 'node'
            |・
            = link_to @topic.user.name, @topic.user, class: 'user'
            |・
            = "created at #{time_ago_in_words @topic.created_at}"
            |・
            |Last by
            a<> href='/ui/user' roybums
            |Replied at 3days ago
        .media-right
          a href='#'
            = image_tag letter_avatar_url('hzbook')
      .panel-body
        article = simple_format @topic.body
        
    #replies.panel.panel-default
      .panel-heading.total = "共收到 #{number_with_delimiter @topic.replies.size} 条回复"
      .media-list style='margin-top: 15px;'
        - @topic.replies.each do |reply|
          .reply.media
            .media-left
              = image_tag letter_avatar_url('lgn21st', 48), class: 'avatar'
            .media-body
              .media-heading.infos
                a href='/ui/user' lgn21st
                |・
                = "回复于 #{time_ago_in_words reply.created_at} 之前"
              .content = simple_format reply.content
              
    #new_reply.panel.panel-default
      .panel-heading 回帖
      .panel-body
        form.form
        = form_for [@topic, Reply.new] do |f|
          .form-group
            = f.text_area :content, class: 'form-control', rows: 4
          .form-group
            = f.submit '回复', class: 'btn btn-success'
            
  .col-md-3
    #topic-sidebar
      .panel.panel-default
        .panel-body
          .row
            .col-md-12.text-center
              .total 共收到 33 条回复
            .col-md-12
              a.btn.btn-success.btn-block href='#' 参与回复
              

app/views/ui/index.html.slim
ul
  - Dir.glob('app/views/ui/*.html.slim').sort.each do |file|
    - basename = File.basename(file, '.html.slim')
    - unless basename == 'index' || basename.start_with?('_')
      li = link_to basename.titleize, action: basename

app/views/ui/new_topic.html.slim
.panel.panel-default
  .panel-heading 发布新话题
  .panel-body
    .form-group
      .row
        .col-md-2
          select.form-control
            option 选择节点
            option value='Ruby' Ruby
            option value='Rails' Rails
            option value='瞎扯淡' 瞎扯淡
        .col-md-10
          = text_field_tag 'title', '', class: 'form-control', placeholder: '在这里填写标题'
    .form-group
      = text_area 'body', '', rows: 20, class: 'form-control'
    .form-group
      .row
        .col-md-2
          a.btn.btn-primary.btn-block 保存
        

app/views/ui/node.html.slim
.row
  .col-md-9
    .panel.panel-default
      .panel-heading
        .node-info
          .name
            strong 书籍
            span.total 共有 167 个讨论主题
          .summary
            p 我爱阅读
      .panel-body.topics
        .media-list
          .media.topic
            .media-left
              a href='#'
                = image_tag letter_avatar_url('hzbook')
            .media-body
              h4.media-heading
                a href='#' 《Effective Ruby：改善 Ruby 程序的 48 条建议》Effective Software Development Series” 系列经典著作 
              .info
                a href='hzbook' hzbook
                |・创建于 4 天之前
                |・最后由
                a<> href='monsoon137' monsoon137
                |回复于 3 天之前
            .media-right
              .badge.badge-default.count 30
          .media.topic
            .media-left
              a href='#'
                = image_tag letter_avatar_url('ibcker')
            .media-body
              h4.media-heading
                a href='#' 有一打《Effective Ruby》要送给你，你不要，怪我咯~
              .info
                a href='ibcker' ibcker
                |・创建于 4 天之前
                |・最后由
                a<> href='monsoon137' monsoon137
                |回复于 3 天之前
            .media-right
              .badge.badge-default.count 111
          .media.topic
            .media-left
              a href='#'
                = image_tag letter_avatar_url('andor_chen')
            .media-body
              h4.media-heading
                a href='#' [结束] 送几本《Docker 即学即用》
              .info
                a href='andor_chen' andor_chen
                |・创建于 4 天之前
                |・最后由
                a<> href='monsoon137' monsoon137
                |回复于 3 天之前
            .media-right
              .badge.badge-default.count 110

  .col-md-3
    .panel.panel-default
      .panel-body.text-center
        .row
          .col-md-12
            a href='/ui/new_topic' class='btn btn-primary btn-block' 发表新帖子
    .panel.panel-default
      .panel-heading 会员信息
      ul.list-group
        li.list-group-item 社区会员: 25426 人
        li.list-group-item 帖子数: 29278 个
        li.list-group-item 回帖数: 290719 条

app/views/ui/signin.html.slim
.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading 登录
      .panel-body
        form.form
          .form-group
            input.form-control type='email' placeholder='邮箱地址' 
          .form-group
            input.btn.btn-success.btn-block type='submit' value='登录' data-disable-with='正在提交'
      

app/views/ui/signup.html.slim
.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading 注册新用户
      .panel-body
        form.form
          .form-group
            input.form-control type='text' placeholder='用户名' 
          .form-group
            input.form-control type='email' placeholder='邮箱地址' 
          .form-group
            .row
              .col-md-6
                input.btn.btn-primary.btn-block type='submit' value='注册' data-disable-with='正在提交'
              .col-md-6
                a.btn.btn-success.btn-block 登录
      

app/views/ui/topic.html.slim
.row
  .col-md-9
    .panel.panel-default.topic-detail
      .panel-heading.media
        .media-body
          h1.media-heading 《Effective Ruby：改善 Ruby 程序的 48 条建议》Effective Software Development Series” 系列经典著作
          .info
            a.node href='/ui/node' 书籍
            |・
            a.user href='/ui/user' hzbook
            |・创建于 20 天之前
            |・最后由
            a<> href='/ui/user' roybums
            |回复于 3 天之前
        .media-right
          a href='#'
            = image_tag letter_avatar_url('hzbook')
      .panel-body
        article
          p
            a href='https://ruby-china-files.b0.upaiyun.com/photo/2016/dbb170078a7d238de732de106ebfd9d7.jpg'
              img src="https://ruby-china-files.b0.upaiyun.com/photo/2016/dbb170078a7d238de732de106ebfd9d7.jpg" alt="" style="opacity: 1;"
          p
            strong 
              |从模块、内存到元编程，全面总结和探讨Ruby编程中48个鲜为人知和容易被忽视的特性与陷阱
              br
              |包含大量实用范例代码，为编写易于理解、便于维护、易于扩展和高效的Ruby应用提供了解决方案

          p
            strong
              |书         名：
              a href="http://item.jd.com/11846515.html" Effective Ruby：改善Ruby程序的48条建议
            br
            strong 
              原文书名：Effective Ruby: 48 Specific Ways to Write Better Ruby
              作者：[美] 彼得 J.琼斯( Peter J. Jones）著<br>
              译者：刘璐 杨政权 秦五一 孟樊超 译</p>

          p
            如果你是经验丰富的Ruby程序员，本书能帮助你发挥Ruby的全部力量来编写更稳健、高效、可维护和易执行的代码。Peter J.Jones凭借其近十年的Ruby开发经验，总结出48条Ruby的最佳实践、专家建议和捷径，并辅以可执行的代码实例。<br
            Jones在Ruby开发的每个主要领域都给出了实用的建议，从模块、内存到元编程。他对鲜为人知的Ruby方言、怪癖、误区和强力影响代码行为与性能的复杂性的揭示贯穿全书。
            每一条都包括具体的、可执行的、清晰组织的指南，还有精细的建议、详尽的技术讨论以及启发性的代码实例。如果存在多种可选方案，Jones也会讲解在特定情况下如何选择最优方案。
            本书将帮助你系统性地改进代码，不是让你盲从准则，而是通过透彻地理解Ruby编程技术来做到这些。

          p
            推荐阅读：
            br
            a href="http://item.jd.com/11864820.html" target="_blank" Effective Python：编写高质量Python代码的59个有效方法
            br
            a href="http://item.jd.com/11402853.html" target="_blank" Effective Objective-C 2.0：编写高质量iOS与OS X代码的52个有效方法
            br
            a href="http://item.jd.com/11354665.html" target="_blank" Effective JavaScript: 编写高质量JavaScript代码的68个有效方法
            br
            a href="http://item.jd.com/10058902.html" target="_blank" Effective Java中文版 第2版
    #replies.panel.panel-default
      .panel-heading.total 共收到 33 条回复
      .media-list style='margin-top: 15px;'
        .reply.media
          .media-left
            = image_tag letter_avatar_url('lgn21st', 48), class: 'avatar'
          .media-body
            .media-heading.infos
              a href='/ui/user' lgn21st
              |・
              |20 days ago
            .content 这本书的翻译出版对 Ruby 中文社区来说，是一件大好事，置顶支持一下。
        .reply.media
          .media-left
            = image_tag letter_avatar_url('cqcn1991', 48), class: 'avatar'
          .media-body
            .media-heading.infos
              a href='/ui/user' cqcn1991
              |・
              |20 days ago
            .content
              |我记得还有相应的视频，之前找了下，可惜一直没时间看
              br
              a href='http://www.informit.com/store/effective-ruby-livelessons-video-training-downloadable-9780134175379' http://www.informit.com/store/effective-ruby-livelessons-video-training-downloadable-9780134175379
        .reply.media
          .media-left
            = image_tag letter_avatar_url('fighterleslie', 48), class: 'avatar'
          .media-body
            .media-heading.infos
              a href='/ui/user' fighterleslie
              |・
              |20 days ago
            .content
              |Effective 系列确实都是好书！
        .reply.media
          .media-left
            = image_tag letter_avatar_url('wwwicbd', 48), class: 'avatar'
          .media-body
            .media-heading.infos
              a href='/ui/user' wwwicb
              |・
              |19 days ago
            .content
              |有电子版就更好了
        .reply.media
          .media-left
            = image_tag letter_avatar_url('xmonkeycn', 48), class: 'avatar'
          .media-body
            .media-heading.infos
              a href='/ui/user' xmonkeycn
              |・
              |19 days ago
            .content
              |kindle出来马上买，期待。
        .reply.media
          .media-left
            = image_tag letter_avatar_url('adamshen', 48), class: 'avatar'
          .media-body
            .media-heading.infos
              a href='/ui/user' adamshen
              |・
              |17 days ago
            .content
              |还是买实体书吧，matz的书我就是kindle上买的，看代码真心不方便。
            
    #new_reply.panel.panel-default
      .panel-heading 回帖
      .panel-body
        form.form
          .form-group
            textarea class='form-control' rows='4'
          .form-group
            button.btn.btn-success 回复
  .col-md-3
    #topic-sidebar
      .panel.panel-default
        .panel-body
          .row
            .col-md-12.text-center
              .total 共收到 33 条回复
            .col-md-12
              a.btn.btn-success.btn-block href='#' 参与回复
              

app/views/ui/topics.html.slim
.row
  .col-md-9
    .panel.panel-default
      .panel-heading 全部帖子
      .panel-body.topics
        .media-list
          .media.topic
            .media-left
              a href='#'
                = image_tag letter_avatar_url('hzbook')
            .media-body
              h4.media-heading
                a href='#' 《Effective Ruby：改善 Ruby 程序的 48 条建议》Effective Software Development Series” 系列经典著作 
              .info
                a.node href='#' 书籍
                |・
                a href='hzbook' hzbook
                |・创建于 4 天之前
                |・最后由
                a<> href='monsoon137' monsoon137
                |回复于 3 天之前
            .media-right
              .badge.badge-default.count 30
          .media.topic
            .media-left
              a href='#'
                = image_tag letter_avatar_url('rei')
            .media-body
              h4.media-heading
                a href='#' 《提问的智慧》 
              .info
                a.node href='#' 其他
                |・
                a href='rei' rei
                |・创建于 4 天之前
                |・最后由
                a<> href='kirahu' kirahu
                |回复于 4 天之前
            .media-right
              .badge.badge-default.count 33
          .media.topic
            .media-left
              a href='#'
                = image_tag letter_avatar_url('benx')
            .media-body
              h4.media-heading
                a href='#' [成都] 热音公司招聘 Ruby 工程师 2 名
              .info
                a.node href='#' 招聘
                |・
                a href='benx' benx
                |・创建于 4 天之前
                |・最后由
                a<> href='kirahu' kirahu
                |回复于 4 天之前
            .media-right
              .badge.badge-default.count 9
          .media.topic
            .media-left
              a href='#'
                = image_tag letter_avatar_url('rails_on_li')
            .media-body
              h4.media-heading
                a href='#' rvm -v 命令
              .info
                a.node href='#' RVM/Rbenv
                |・
                a href='rails_on_li' rails_on_li
                |・创建于 4 天之前
                |・最后由
                a<> href='kirahu' kirahu
                |回复于 4 天之前
            .media-right
              .badge.badge-default.count 84

    .panel.panel-default
      .panel-heading 节点列表
      .panel-body.node-list
        span.node-item
          a href='/topics/node1' 重构
        span.node-item
          a href='/topics/node2' Rails
        span.node-item
          a href='/topics/node3' RVM/Rbenv
        span.node-item
          a href='/topics/node4' JRuby
        span.node-item
          a href='/topics/node5' 新手问题
        span.node-item
          a href='/topics/node6' Gem
        span.node-item
          a href='/topics/node7' 开源项目
        span.node-item
          a href='/topics/node8' 部署
      
  .col-md-3
    .panel.panel-default
      .panel-body.text-center
        .row
          .col-md-12
            a href='/ui/new_topic' class='btn btn-primary btn-block' 发表新帖子
    .panel.panel-default
      .panel-heading 会员信息
      ul.list-group
        li.list-group-item 社区会员: 25426 人
        li.list-group-item 帖子数: 29278 个
        li.list-group-item 回帖数: 290719 条

app/views/ui/user.html.slim
.row
  .col-md-4
    .panel.panel-default
      .panel-body
        .media
          .media-left
            = image_tag letter_avatar_url('blueplanet')
          .media-body
            |blueplanet
            br
            |第 2650 位用户
            br
            |注册时间 2012-06-25
            br
            |20 篇帖子・143 条回帖
              
  .col-md-8
    ul.nav.nav-tabs
      li.active: a href='#' 个人信息
      li: a href='/ui/user_topics' 帖子
      li: a href='/ui/user_replies' 回帖
    .panel.panel.default
      .panel-body
        dl.dl-horizontal
          dt Twitter
          dd @blueplanet42

app/views/ui/user_replies.html.slim
#user
  .row
    .col-md-4
      .panel.panel-default
        .panel-body
          .media
            .media-left
              = image_tag letter_avatar_url('blueplanet')
            .media-body
              |blueplanet
              br
              |第 2650 位用户
              br
              |注册时间 2012-06-25
              br
              |20 篇帖子・143 条回帖
                
    .col-md-8
      ul.nav.nav-tabs
        li: a href='/ui/user' 个人信息
        li: a href='/ui/user_topics' 帖子
        li.active: a href='#' 回帖
      .panel.panel.default
        .panel-body
          ul.list-group
            li.list-group-item
              .title
                a href='/ui/topic' 关于在 Rails Model 中使用 Enum (枚举) 的若干总结 
                em at 2 months ago
              .body.markdown
                p 补充几个踩过的坑
                p 定义enum时自动增加的各个值对应的?和!方法是model范围内有效的。如果不同的字段有同名的值的时候一定要注意
                pre
                  |
                    # user.rb
                    enum status: [:temporary, :active, :deleted]
                    enum admin_status: [:active, :super_admin]

                    # rails console
                    irb(main):001:0> u = User.neww
                    ArgumentError: You tried to define an enum named "admin_status" on the model "User", but this will generate a instance method "active?", which is already defined by another enum.
                    修改以前定义好的enum时需要注意历史数据
                    # 原来是这样的定义
                    enum status: [:temporary, :active, :deleted]
                    # 修改后,
                    enum status: [:temporary, :active, :waiting, :deleted]
                    # 如果这样修改的话，以前的`deleted`的数据修改后就变成`:waiting`了！！！ :sleepy: 
                p 所以，不推荐使用[:temporary, :active, :deleted]的方式，尽量使用{ temporary: 1, active: 2, deleted: 3]这样的明确定义数值的方式
            li.list-group-item
              .title
                a href='/ui/topic' 准备着手翻译出版《Rebuilding Rails》，有人愿意买吗？ 
                em at 2 months ago
              .body.markdown 必须买！也希望是电子版！
            li.list-group-item
              .title
                a href='/ui/topic' Ruby 基础 - RubyGem，如何开发一个自己的 Gem
                em at 8 months ago
              .body.markdown 
                p
                  |
                    @cicholgricenchos 你的问题属于git的问题吧。
                    在空文件夹里创建一个零字节的文件就成。
                    按惯例一般是.gitkeep

app/views/ui/user_topics.html.slim
#user
  .row
    .col-md-4
      .panel.panel-default
        .panel-body
          .media
            .media-left
              = image_tag letter_avatar_url('blueplanet')
            .media-body
              |blueplanet
              br
              |第 2650 位用户
              br
              |注册时间 2012-06-25
              br
              |20 篇帖子・143 条回帖
                
    .col-md-8
      ul.nav.nav-tabs
        li: a href='/ui/user' 个人信息
        li.active: a href='#' 帖子
        li: a href='/ui/user_replies' 回帖
      .panel.panel.default
        .panel-body
          table.table.topics
            tr.topic
              td.node
                a href='/ui/node' 书籍
              td.title
                a href='/ui/topic' 类似 “按照最新发布文章时间排序的用户列表” 的优雅的实现方法 
                em 10 months ago
              td.replies 2/0
            tr.topic
              td.node
                a href='/ui/node' Rails
              td.title
                a href='/ui/topic' [已解决]使用 Ajax 时遇到了 InvalidAuthenticityToken 错误 
                em 2 years ago
              td.replies 8/0
            tr.topic
              td.node
                a href='/ui/node' Testing
              td.title
                a href='/ui/topic' feature spec / integration spec( request spec) / controller spec 的区别 
                em 2 years ago
              td.replies 2/2
            tr.topic
              td.node
                a href='/ui/node' 新手问题
              td.title
                a href='/ui/topic' 网页上想要的效果和 Model 的对应关系弄不明白了 
                em 3 years ago
              td.replies 12/0

app/views/users/_basic_info.html.slim
.panel.panel-default
  .panel-body
    .media
      .media-left
        = image_tag letter_avatar_url(user.name)
      .media-body
        = user.name
        br
        |第 2650 位用户
        br
        = "注册时间 #{l user.created_at.to_date, format: :long}"
        br
        |20 篇帖子・143 条回帖

app/views/users/new.html.slim
.row
  .col-md-6.col-md-offset-3
    .panel.panel-default
      .panel-heading 注册新用户
      .panel-body
        = form_for @user, class: 'form' do |f|
          .form-group
            = f.text_field :name, class: 'form-control', placeholder: '用户名'
          .form-group
            = f.text_field :email, class: 'form-control', placeholder: '邮箱地址'
          .form-group
            .row
              .col-md-6
                = f.submit '注册', class: 'btn btn-primary btn-block', data: { 'disable-with' => '正在提交'}
              .col-md-6
                a.btn.btn-success.btn-block 登录
      

app/views/users/show.html.slim
.row
  .col-md-4
    = render 'basic_info', user: @user
              
  .col-md-8
    ul.nav.nav-tabs
      li.active
        = link_to '个人信息', @user
      li
        = link_to '帖子', user_topics_path(@user)
      li: a href='/ui/user_replies' 回帖
    .panel.panel.default
      .panel-body
        dl.dl-horizontal
          dt Twitter
          dd @blueplanet42

app/views/users/topics.html.slim
#user
  .row
    .col-md-4
      = render 'basic_info', user: @user  
      
    .col-md-8
      ul.nav.nav-tabs
        li = link_to '个人信息', @user
        li.active = link_to '帖子', user_topics_path(@user)
        li: a href='/ui/user_replies' 回帖
      .panel.panel.default
        .panel-body
          table.table.topics
            - @user.topics.each do |topic|
              tr.topic
                td.node
                  = link_to topic.node.name, topic.node
                td.title
                  = link_to topic.title, topic
                  em = "创建于 #{time_ago_in_words topic.created_at} 之前"
                td.replies 2/0